version: '3.8'

services:
  backend:
    build: .
    ports:
      - "1034:443"  # Map external 1035 to internal 443 for HTTPS
      - "1034:80"   # Map external 1035 to internal 80 for HTTP
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - HTTPS_PORT=443
      - HTTP_PORT=80
